### ISSUE TITLE
azure-pipelines for repo a broken

### ISSUE THREAD

**Issue by remvee** [iSHAREScheme/Documentation#18]
Version of python needed is no longer supported.  See also:

> azure-pipelines / iSHAREScheme.Documentation
> 
> Build log #L10
> 
> Failed to download Python from the Github Actions python registry (https://github.com/actions/python-versions). Error: Error: Could not find Python matching spec 3.6 (x64) in the python-versions registry. Beware that only systems listed in the Github Actions python versions manifest (https://github.com/actions/python-versions/blob/main/versions-manifest.json) are fit for downloading python on-flight. Also, proxy is not supported.

and

> azure-pipelines / iSHAREScheme.Documentation
> 
> Build log #L11
> 
> Version spec 3.6 for architecture x64 did not match any version in Agent.ToolsDirectory.
> Versions in /opt/hostedtoolcache:
> 
> 3.10.11 (x64)
> 3.11.3 (x64)
> 3.7.16 (x64)
> 3.8.16 (x64)
> 3.9.16 (x64)
> If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
> If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
> 
>

**Comment by rajiv-ishare** [comment]
Fixed in PR22
